# Generated by Django 5.1.4 on 2024-12-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_user_id_orders_user_remove_orders_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
