# Generated by Django 5.1.4 on 2024-12-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
