# Generated by Django 5.1.4 on 2024-12-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_is_available_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
