# Generated by Django 5.1.4 on 2024-12-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
