# Generated by Django 5.1.4 on 2024-12-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_image_products_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
